/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./../components/Dialog/index.vue')['default']
    Empty: typeof import('./../components/Empty/Empty.vue')['default']
    Header: typeof import('./../components/Header/Header.vue')['default']
    HeaderXcx: typeof import('./../components/Header/HeaderXcx.vue')['default']
    List: typeof import('./../components/List/List.vue')['default']
    ListState: typeof import('./../components/ListState/ListState.vue')['default']
    ListTwo: typeof import('./../components/List/ListTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
